markdown            : kramdown
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes

# repository: dm-17/Owasp-BeNeLux-Days-2025

# Since GH pages override this to "true", we test this value to see if we are running locally
safe: false


# baseurl: /

# multiply: url(assets/images/simpleback.svg)

excerpt_separator: <!--more-->

sass:
  sass_dir: assets/_sass

# checkmarkimg: <img class="checkmark" alt="checkmark" />

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  # -
  #   scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     layout: "post"
